version: "3.9"

volumes:
  data: {}

services:
  data:
    build:
      context: .
      dockerfile: Dockerfile.data
    volumes:
      - type: volume
        source: data
        target: /data
        # volume:
        #   nocopy: true
      # - type: bind
      #   source: ./static
      #   target: /opt/app/static
  app:
    image: alpine
    # command: "sleep infinity"
    volumes:
      - data:/data

