FROM alpine:3.13

RUN apk --update --no-cache add \
	    curl \
      bash \
      netcat-openbsd

SHELL ["bash", "-c"]

COPY ./server-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
