# vim:set ft=dockerfile:
FROM andrius/crystal-lang as builder

LABEL maintainer="Andrius Kairiukstis <k@andrius.mobi>"

WORKDIR /src
COPY . .

RUN shards build --production --progress --verbose --warnings=all
RUN ldd ./bin/signal_trap | tr -s '[:blank:]' '\n' | grep '^/' | \
    xargs -I % sh -c 'mkdir -p $(dirname deps%); cp % deps%;'

################################################################################
FROM scratch

LABEL maintainer="Andrius Kairiukstis <k@andrius.mobi>"

# dependences
COPY --from=builder /src/deps /
# that will fix DNS resolve issue in docker
COPY --from=builder /lib/x86_64-linux-gnu/libnss_dns.so.* /lib/x86_64-linux-gnu/
COPY --from=builder /lib/x86_64-linux-gnu/libresolv.so.*  /lib/x86_64-linux-gnu/

# app
COPY --from=builder /src/bin/signal_trap /signal_trap

ENTRYPOINT ["/signal_trap"]
